const history = [
  {
    id: 123,
    status: 'success',
    message: 'add documentation for postgres scaler',
    branch: 'master',
    hash: '9c9f0b9',
    user: 'Philip Kirkorov',
    timestamp: '21 янв, 03:06',
    timePassed: '1 ч 20 мин',
  },
  {
    id: 234,
    status: 'pending',
    message: 'add documentation for postgres scaler',
    branch: 'master',
    hash: '9c9f0b9',
    user: 'Philip Kirkorov',
    timestamp: '21 янв, 03:06',
    timePassed: '1 ч 20 мин',
  },
  {
    id: 345,
    status: 'failure',
    message: 'add documentation for postgres scaler',
    branch: 'master',
    hash: '9c9f0b9',
    user: 'Philip Kirkorov',
    timestamp: '21 янв, 03:06',
    timePassed: '1 ч 20 мин',
  },
  {
    id: 456,
    status: 'failure',
    message: 'add documentation for postgres scaler',
    branch: 'master',
    hash: '9c9f0b9',
    user: 'Philip Kirkorov',
    timestamp: '21 янв, 03:06',
    timePassed: '1 ч 20 мин',
  },
  {
    id: 567,
    status: 'failure',
    message: 'add documentation for postgres scaler',
    branch: 'master',
    hash: '9c9f0b9',
    user: 'Philip Kirkorov',
    timestamp: '21 янв, 03:06',
    timePassed: '1 ч 20 мин',
  },
];

export default history;
